module.exports={
	"anmo":{
		title:"按摩",
		headimg:["/assets/static/images/baomu_1.png"],
		standard:"响应迅速,上门服务有保障。助家生活上门按摩,100%技师认证,安全、专业!旨在提供更好的上门按摩服务。",
		introduce:"",
		range:"",
		price:"",
		process:"",
		assurance:[
			{t:"健康保障",c:"服务人员均通过健康认证，每年进行2次健康检查，保障雇主家庭健康安全！"},
			{t:"隐私保障",c:"服务过程中，未经客户允许，不擅自翻动衣柜、抽屉等个人隐私范围，不泄露客户个人隐私！"}
		]
	},
	"yuesao":{
		title:"月嫂",
		headimg:["/assets/static/images/header-ys.png"],
		standard:"",
		introduce:{
			title:"经助家认证的月嫂，依托专业辅导团队、既为产妇提供健康膳食、起居护理、形体恢复、心理疏导等服务，也为新生儿提供身体护理、健康喂养、日常物品清洁等服务。选择专业月嫂，呵护母婴，体贴放心。",
			img:"/assets/static/images/yuersao_1.png"
		},
		range:[
			[{
				title:"新生儿生活护理",
				img:"/assets/static/images/range-ys-1.png"
			},{
				title:"产妇生活护理",
				img:"/assets/static/images/range-ys-2.png"
			}],
			[{
				title:"健康指导",
				img:"/assets/static/images/range-ys-3.png"
			},{
				title:"日常服务",
				img:"/assets/static/images/range-ys-4.png"
			}]
		],
		price:"/assets/static/images/price-bg-ys.png",
		process:"/assets/static/images/process-ys.png",
		assurance:[
			{t:"健康保障",c:"服务人员均通过健康认证，每年进行2次健康检查，保障雇主家庭健康安全！"},
			{t:"隐私保障",c:"服务过程中，未经客户允许，不擅自翻动衣柜、抽屉等个人隐私范围，不泄露客户个人隐私！"}
		]
	}
}
